### ISSUE TITLE
TODO List mode.

### ISSUE THREAD

**Issue by toastkidjp** [toastkidjp/Yobidashi_kt#625]
## Features

- [ ] Draggable note board
- [ ] List
- [ ] Removable
- [ ] Enable set color
- [ ] Enable to notify
- [ ] Sort
- [ ] Filter...Keyword, Category, and so on...
- [ ] Import & Export

### ToDoTask

| Name | Type
|:---|:---
| id | Int(Primary key & Auto generate)
| description | String
| created | Long
| modified | Long
| due_date | Long
| categoryId | Int
| color | Int
| x | Int
| y | Int
| boardId | Int
| done | Boolean

### Board

| Name | Type
|:---|:---
| id | Int(Primary key & Auto generate)
| name | String
| description | String
| created | Long
| modified | Long

### Category

| Name | Type
|:---|:---
| id | Int(Primary key & Auto generate)
| name | String
| description | String
| created | Long
| modified | Long

**Comment by toastkidjp** [comment]
![fts](https://user-images.githubusercontent.com/15980475/94365777-89eb4800-010e-11eb-8604-67896bd06545.gif)
![like](https://user-images.githubusercontent.com/15980475/94365780-8bb50b80-010e-11eb-926d-05a9f7011884.gif)
